url: https://epochml.org
baseurl: /

# Site settings
title: Epoch
email: help@epochml.org
description: "EpochML is building a computational cluster for the IMSA community."


# Team names, titles and social links
motherboard:
- name: Gautham Anne
  pic: gautham.png
  position: CEO
  social:
    - title: fas fa-envelope
      url: mailto:ganne@epochml.org
- name: Braeden Cullen
  pic: dne.jpg
  position: CTO
  social:
    - title: fas fa-envelope
      url: mailto:bcullen@epochml.org
    - title: fab fa-github
      url: https://github.com/BraedenCu
- name: Shria Halkoda
  pic: dne.jpg
  position: CSO
  social:
    - title: fas fa-envelope
      url: mailto:shalkoda@epochml.org
- name: Bhavyaa Chauhan
  pic: dne.jpg
  position: CFO
  social:
    - title: fas fa-envelope
      url: mailto:bchauhan@epochml.org
- name: Melanie Cuenca
  pic: melanie.jpg
  position: CRO
  social:
    - title: fas fa-envelope
      url: mailto:mcuenca@epochml.org  


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: discord
    url: https://goepoch.ml/discord
  - title: github
    url: https://github.com/epochml

# Postal address (add as many lines as necessary)
address:
  - line: 1500 Sullivan Road
  - line: Aurora, IL 60506

# Build settings
markdown: kramdown
permalink: pretty
